
builders:

  copyrightBuilder:
    import: "package:dotup_dart_copyright_builder/builder.dart"
    builder_factories: ["copyrightBuilder"]
    build_extensions: {".dart": [".copyright.dart"]}
    build_to: source
    auto_apply: root_package
    applies_builders: ["copyrightBuilder"]
    defaults:
      options:
        force: false
        enabled: true
        copyright: "Copyright dotup IT solutions - Peter Ullrich"
        text: [
          "// More text",
          "// More text",
          "// More text",
        ]

