name: dotup_dart_copyright_builder
description: Generates copyright header for each dart file
version: 1.0.1
homepage: https://dotup.de
repository: https://github.com/dotupNET/dotup_dart_copyright_generator

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.5
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  build: ^2.1.1
